openapi: 3.0.0
info:
  title: Redemption API
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /redemptions/prepare:
    post:
      summary: Prepare a redemption request
      operationId: prepareRedemption
      tags:
        - Redemption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  description: ID of the customer initiating the redemption
                assetId:
                  type: string
                  description: ID of the asset to be redeemed
                quantity:
                  type: integer
                  description: Quantity of the asset to be redeemed
              required:
                - customerId
                - assetId
                - quantity
      responses:
        '201':
          description: Redemption request prepared successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Redemption'
        '400':
          description: Invalid request body
  /redemptions/{id}/commit:
    put:
      summary: Commit a prepared redemption request
      operationId: commitRedemption
      tags:
        - Redemption
      parameters:
        - name: id
          in: path
          description: ID of the prepared redemption request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Redemption request committed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Redemption'
        '404':
          description: Redemption request not found
        '409':
          description: Redemption request conflict (e.g. already committed or expired)
components:
  schemas:
    Redemption:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the redemption request
        customerId:
          type: string
          description: ID of the customer initiating the redemption
        assetId:
          type: string
          description: ID of the asset being redeemed
        quantity:
          type: integer
          description: Quantity of the asset to be redeemed
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the redemption was prepared
        status:
          type: string
          description: Status of the redemption (e.g., 'prepared', 'committed')
